version: '3.8'

services:
  pagopa-ecommerce-helpdesk-commands-service:
    container_name: pagopa-ecommerce-helpdesk-commands-service
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    networks:
      - pagopa-ecommerce-net
  pagopa-npg-mock:
    build:
      context: .
      dockerfile: npg-mock/Dockerfile.npg-mock
    container_name: pagopa-NPG-mock-helpdesk-cmd
    volumes:
      - type: bind
        source: ./npg-mock
        target: /config
        read_only: true
    ports:
      - "3000:3000"
    networks:
      - pagopa-ecommerce-net
  pagopa-redirect-mock:
    build:
      context: .
      dockerfile: redirect-mock/Dockerfile.redirect-mock
    container_name: pagopa-REDIRECT-mock-helpdesk-cmd
    volumes:
      - type: bind
        source: ./redirect-mock
        target: /config
        read_only: true
    ports:
      - "8096:3000"
    networks:
      - pagopa-ecommerce-net

networks:
  pagopa-ecommerce-net:
    name: pagopa-ecommerce-net
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450


