version: '3.8'

services:
  mongo:
    container_name: pagopa-helpdesk-mongo
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - pagopa-ecommerce-net
    ports:
      - "27017:27017"

  pagopa-ecommerce-helpdesk-commands-service:
    container_name: pagopa-ecommerce-helpdesk-commands-service
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    networks:
      - pagopa-ecommerce-net
    depends_on:
      - mongo
    restart: on-failure

  pagopa-npg-mock:
    build:
      context: .
      dockerfile: npg-mock/Dockerfile.npg-mock
    container_name: pagopa-NPG-mock-helpdesk-cmd
    volumes:
      - type: bind
        source: ./npg-mock
        target: /config
        read_only: true
    ports:
      - "3000:3000"
    networks:
      - pagopa-ecommerce-net

  pagopa-psp-mock:
    build:
      context: .
      dockerfile: psp-mock/Dockerfile.psp-mock
    volumes:
      - type: bind
        source: ./psp-mock
        target: /config
        read_only: true
    ports:
      - "8096:3000"
    networks:
      - pagopa-ecommerce-net

networks:
  pagopa-ecommerce-net:
    name: pagopa-ecommerce-net
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  mongodb_data: