parameters:
  # Required
  - name: "ENV_FILE"
    type: string
  - name: "API_TEST_FILE"
    type: string
  - name: "TEST_FILE_PREFIX"
    type: string
  - name: "API_SUBSCRIPTION_KEY"
    type: string
    default: ' '

steps:
  - script: |
      yarn global add newman
    displayName: 'Newman installation'
  - script: |
      newman run ${{ parameters.API_TEST_FILE }} -e ${{ parameters.ENV_FILE }} --env-var API_SUBSCRIPTION_KEY=${{ parameters.API_SUBSCRIPTION_KEY }} --ignore-redirects --reporters cli,junit --reporter-junit-export Results/${{ parameters.TEST_FILE_PREFIX }}-api-TEST.xml
    displayName: 'Run api test'
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*-TEST.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'